# Generated by Django 5.2.5 on 2025-09-01 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCIAParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', help_text='Legal first name.', max_length=1000, verbose_name='First Name✽')),
                ('last_name', models.CharField(blank=True, default='', help_text='Legal last name.', max_length=1000, verbose_name='Last Name✽')),
                ('suffix', models.CharField(blank=True, default='', help_text='Legal name suffix if necessary (e.g. "III", "Jr.", "Sr.", etc.).', max_length=100, verbose_name='Suffix')),
                ('preferred_name', models.CharField(blank=True, default='', help_text='If you have another first name that you would prefer to be called that is different than your legal first name, please enter it here. (NOTE: You can leave this field blank if your preferred name is the same as your first name listed above.', max_length=1000, verbose_name='Preferred Name')),
                ('email', models.CharField(blank=True, default='', help_text='Your email address.', max_length=1000, verbose_name='Email Address✽')),
                ('phone', models.CharField(blank=True, default='', help_text='Provide a good contact number (preferably one that can send and receive texts).', max_length=20, verbose_name='Phone Number')),
                ('can_text', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text='Can your phone and receive and send text messages?', max_length=10, verbose_name='Can Text?')),
                ('mailing_address', models.TextField(blank=True, default='', help_text='Full mailing address, city, state, zip code.', verbose_name='Mailing Address')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of your birth.', null=True, verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(blank=True, default='', help_text='City, state (and country if other than the US) where you were born.', max_length=1000, verbose_name='Place of Birth')),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', help_text='Biological sex.', max_length=10, verbose_name='Sex')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], default='', help_text='Are you currently single or married? NOTE: If you are separated from your spouse but have not gotten a divorce, please answer "Married".', max_length=10, verbose_name='Current Marital Status')),
                ('num_marriages', models.CharField(blank=True, default='', help_text='Indicate the total number of times you have been married. Please include your current marriage in this count (if you are married now).', max_length=10, verbose_name='Number of Marriages✽')),
                ('engaged', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text='If not married, are you are engaged to be married?', max_length=10, verbose_name='Engaged?✽')),
            ],
            options={
                'verbose_name': 'OCIA Participant',
                'verbose_name_plural': 'OCIA Participants',
            },
        ),
        migrations.CreateModel(
            name='OCIAParticipantEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiance_name', models.CharField(blank=True, default='', help_text="Your fiance's full name.", max_length=1000, verbose_name="Fiance's Full Name")),
                ('planned_date_of_marriage', models.DateField(blank=True, help_text='Date you are planning to get married (if known).', null=True, verbose_name='Planned Date of Marriage')),
                ('fiance_religion', models.CharField(blank=True, default='', help_text="What is your fiance's religious affiliation?", max_length=1000, verbose_name="Fiance's Religious Affiliation")),
                ('your_first_marriage', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text='Will this be your first marriage?', max_length=10, verbose_name='Your First Marriage?')),
                ('fiance_first_marriage', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text="Will this be your fiance's first marriage?", max_length=10, verbose_name="Fiance's First Marriage?")),
                ('notes', models.TextField(blank=True, default='', help_text='Record any additional notes you think may be important.', verbose_name='Marriage Details')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Record any private / admin notes.', verbose_name='Admin Notes')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='ocia_participant.ociaparticipant')),
            ],
            options={
                'verbose_name': 'OCIA Participant Engagement',
                'verbose_name_plural': 'OCIA Participant Engagement',
            },
        ),
        migrations.CreateModel(
            name='OCIAParticipantMarriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(blank=True, default='', help_text="Your spouse's full name.", max_length=1000, verbose_name="Spouse's Full Name")),
                ('status', models.CharField(blank=True, choices=[('married', 'Currently married'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('deceased', 'Spouse is deceased')], default='', help_text='Current state of the marriage.', max_length=10, verbose_name='Marriage Status')),
                ('date_of_marriage', models.DateField(blank=True, help_text='Date you were married.', null=True, verbose_name='Date of Marriage')),
                ('date_of_divorce', models.DateField(blank=True, help_text='If divorced, record the date of the legally finalized divorce.', null=True, verbose_name='Date of Divorce')),
                ('spouse_first_marriage', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', help_text="Was this your spouse's first marriage at the time?", max_length=10, verbose_name="Spouse's First Marriage?")),
                ('spouse_religion', models.CharField(blank=True, default='', help_text="What is/was your spouse's religious affiliation?", max_length=1000, verbose_name="Spouse's Religious Affiliation")),
                ('notes', models.TextField(blank=True, default='', help_text='Where was the service held? Was it a Catholic or Christian service? Who was the minister (e.g. priest, pastor, deacon, Justice of the Peace, etc.)? Record any additional notes you may think are significant.', verbose_name='Marriage Details')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Record any private / admin notes.', verbose_name='Admin Notes')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to='ocia_participant.ociaparticipant')),
            ],
            options={
                'verbose_name': 'OCIA Participant Marriage',
                'verbose_name_plural': 'OCIA Participant Marriages',
            },
        ),
        migrations.CreateModel(
            name='OCIAParticipantParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Full name of the parent.', max_length=100, verbose_name="Parent's Full Name")),
                ('relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother')], default='', help_text='Relationship to participant (e.g., mother, father).', max_length=100, verbose_name='Parent Relationship')),
                ('religion', models.CharField(blank=True, default='', help_text='Religious affiliation, if known.', max_length=100, verbose_name="Parent's Religious Affiliation")),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='ocia_participant.ociaparticipant')),
            ],
            options={
                'verbose_name': 'OCIA Participant (Parent Info)',
                'verbose_name_plural': 'OCIA Participant (Parent Info)',
            },
        ),
        migrations.CreateModel(
            name='OCIAParticipantQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_attending_class', models.TextField(blank=True, default='', help_text='What or who has led you to want to know more about the Catholic faith?', verbose_name='Reason for Attending OCIA?')),
                ('religious_education', models.TextField(blank=True, default='', help_text='Describe any religious education you have received, either as a child or as an adult.', verbose_name='Religious Education?')),
                ('questions_or_concerns', models.TextField(blank=True, default='', help_text='Do you have any questions or concerns about the Catholic Church that you would like to have addressed publicly in class, or discretely in a private meeting?', verbose_name='Questions or Concerns?')),
                ('on_becoming_catholic', models.CharField(blank=True, choices=[('unlikely', 'I am not really interested in becoming Catholic'), ('undecided', "I don't really know yet"), ('possible', 'I am interested in possibly becoming Catholic'), ('likely', 'I have every intention of becoming Catholic')], default='', help_text='How likely are you to become Catholic?', max_length=100, verbose_name='On the Possibility of Becoming Catholic?')),
                ('on_becoming_catholic_comments', models.TextField(blank=True, default='', help_text='Can you expound on the the answer you gave in the previous question?', verbose_name='Can You Expound?')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ocia_participant.ociaparticipant')),
            ],
            options={
                'verbose_name': 'OCIA Participant (Questions)',
                'verbose_name_plural': 'OCIA Participant (Questions)',
            },
        ),
        migrations.CreateModel(
            name='OCIAParticipantReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, choices=[('Catholic', 'Christian (Catholic)'), ('Christian', 'Christian (Other)'), ('Judaism', 'Judaism'), ('Islam', 'Islam'), ('Buddhism', 'Buddhism'), ('none', 'None'), ('other', 'Other')], default='', help_text='Are you affiliated with any religious faith?', max_length=100, verbose_name='Religion Affiliation')),
                ('affiliation_other', models.CharField(blank=True, default='', help_text='If religious affiliation is "other" please specify that faith here.', max_length=100, verbose_name='Religion Affiliation Other')),
                ('baptized', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Not sure')], default='', help_text='Have you ever been baptized into any Christian faith?', max_length=10, verbose_name='Are You Baptized?')),
                ('baptized_denomination', models.CharField(blank=True, choices=[('Catholic', 'Catholic'), ('Orthodox', 'Orthodox'), ('Baptist', 'Baptist'), ('Episcopal/Anglican', 'Episcopal/Anglican'), ('Lutheran', 'Lutheran'), ('Reformed/Presbyterian', 'Reformed/Presbyterian'), ('Methodist', 'Methodist'), ('Pentecostal', 'Pentecostal'), ('Non-denominational', 'Non-denominational'), ('other', 'Other')], default='', help_text='Into which Christian faith where you baptized?', max_length=50, verbose_name='Baptism Denomination')),
                ('baptized_denomination_other', models.CharField(blank=True, default='', help_text='If baptized in some other denomination, indicate which one here.', max_length=100, verbose_name='Baptism Denomination Other')),
                ('baptized_on', models.DateField(blank=True, help_text='When were you baptized?', null=True, verbose_name='Date of Baptism')),
                ('baptism_info', models.TextField(blank=True, default='', help_text='Name and location of church where you were baptized. (Please provide as much detail as possible.)', verbose_name='Baptism Details')),
                ('sacrament_of_confession', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Not sure')], default='', help_text='If you were baptized Catholic, did you ever receive the Sacrament of Reconciliation (otherwise known as Confession)?', max_length=10, verbose_name='Sacrament of Confession?')),
                ('sacrament_of_communion', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Not sure')], default='', help_text='If you were baptized Catholic, did you ever receive Holy Communion (otherwise known as the Sacrament of the Eucharist)?', max_length=10, verbose_name='Sacrament of Communion?')),
                ('sacrament_of_confirmation', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Not sure')], default='', help_text='If you were baptized Catholic, did you ever receive the Sacrament of Confirmation?', max_length=10, verbose_name='Sacrament of Confirmation?')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Record any private / admin notes.', verbose_name='Admin Notes')),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='religion', to='ocia_participant.ociaparticipant')),
            ],
        ),
    ]
