# Generated by Django 5.2.5 on 2025-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCIAParticipantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(help_text='Access code required for participants to be able to enter participant data.', verbose_name='Access Code')),
                ('liturgical_year', models.CharField(help_text='OCIA class period (e.g. "2025-26").', verbose_name='Liturgical Year')),
                ('enable_editing', models.BooleanField(verbose_name='Enable Editing')),
            ],
            options={
                'verbose_name': 'OCIA Participant Settings',
                'verbose_name_plural': 'OCIA Participant Settings',
            },
        ),
    ]
