# Generated by Django 5.2.5 on 2025-09-01 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0002_ociaparticipantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ociaparticipant',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='OCIA participant record created on this data/time.', verbose_name='Created On'),
        ),
        migrations.AddField(
            model_name='ociaparticipant',
            name='liturgical_year',
            field=models.CharField(blank=True, default='', help_text='OCIA liturgical year.', max_length=1000, verbose_name='Liturgical Year'),
        ),
    ]
