# Generated by Django 5.2.5 on 2025-09-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0003_ociaparticipant_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ociaparticipant',
            name='email',
            field=models.CharField(blank=True, default='', help_text='Your email address.', max_length=1000, verbose_name='Email✽'),
        ),
        migrations.AlterField(
            model_name='ociaparticipant',
            name='liturgical_year',
            field=models.CharField(blank=True, default='', help_text='OCIA liturgical year.', max_length=1000, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='ociaparticipant',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Provide a good contact number (preferably one that can send and receive texts).', max_length=20, verbose_name='Phone'),
        ),
    ]
