# Generated by Django 5.2.5 on 2025-09-14 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0004_alter_ociaparticipant_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCIAParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Unique identifier for this settings record (not editable).', max_length=100, verbose_name='UID')),
                ('access_code', models.CharField(help_text='Access code required for participant to be able to enter participant data.', verbose_name='Access Code')),
                ('email', models.CharField(help_text='Email address of the participant logged into this session.', verbose_name='Email')),
                ('expires_on', models.DateTimeField(help_text='Date/time this session expires.', verbose_name='Expires On')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, help_text='Session created on this data/time.', verbose_name='Created On')),
                ('ip_address', models.CharField(blank=True, help_text='IP address from which the participant logged in.', max_length=100, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, help_text='User agent string of the browser used by the participant.', max_length=1000, null=True, verbose_name='User Agent')),
                ('is_logged_in', models.BooleanField(default=False, help_text='Indicates whether the participant is currently logged in.', verbose_name='Is Logged In')),
            ],
        ),
    ]
