# Generated by Django 5.2.5 on 2025-09-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0005_ociaparticipantsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ociaparticipantsession',
            options={'verbose_name': 'OCIA Participant Session', 'verbose_name_plural': 'OCIA Participant Sessions'},
        ),
        migrations.AddField(
            model_name='ociaparticipantsession',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Indicates whether this session is valid.', verbose_name='Is Valid'),
        ),
    ]
