# Generated by Django 5.2.5 on 2025-09-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0006_alter_ociaparticipantsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ociaparticipantsession',
            name='state',
            field=models.CharField(blank=True, help_text='Current state of the participant session.', max_length=100, null=True, verbose_name='State'),
        ),
    ]
