# Generated by Django 5.2.5 on 2025-09-15 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0007_ociaparticipantsession_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ociaparticipantsession',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='ocia_participant.ociaparticipant'),
        ),
    ]
