# Generated by Django 5.2.5 on 2026-09-09 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0008_ociaparticipantsession_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCIAParticipantAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('email', models.CharField(db_index=True, max_length=1000)),
                ('purpose', models.CharField(choices=[('existing', 'Existing participant login'), ('new', 'New participant registration')], max_length=20)),
                ('expires_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_on', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='ocia_participant.ociaparticipant')),
            ],
            options={
                'verbose_name': 'OCIA Participant Access Token',
                'verbose_name_plural': 'OCIA Participant Access Tokens',
            },
        ),
    ]
