# Generated by Django 5.2.5 on 2026-09-09 04:46

import django.db.models.functions.text
from django.db import migrations, models


def normalize_participant_emails(apps, schema_editor):
    Participant = apps.get_model('ocia_participant', 'OCIAParticipant')
    records = list(Participant.objects.all().only('id', 'email'))
    ids_by_email = {}

    for participant in records:
        normalized_email = (participant.email or '').strip().lower()
        ids_by_email.setdefault(normalized_email, []).append(participant.id)

    duplicate_groups = {
        email: ids
        for email, ids in ids_by_email.items()
        if len(ids) > 1
    }
    if duplicate_groups:
        details = '; '.join(
            f'{email!r}: participant IDs {ids}'
            for email, ids in sorted(duplicate_groups.items())
        )
        raise RuntimeError(
            'Cannot enforce normalized participant email uniqueness. '
            f'Resolve these duplicate groups first: {details}'
        )

    for participant in records:
        normalized_email = (participant.email or '').strip().lower()
        if participant.email != normalized_email:
            participant.email = normalized_email
            participant.save(update_fields=['email'])

class Migration(migrations.Migration):

    dependencies = [
        ('ocia_participant', '0009_ociaparticipantaccesstoken'),
    ]

    operations = [
        migrations.RunPython(
            normalize_participant_emails,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='ociaparticipant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('email')), name='ocia_participant_email_normalized_unique'),
        ),
    ]
