# Generated by Django 5.2.5 on 2025-09-06 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaExplorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Media explorer',
            },
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=250, unique=True, verbose_name='URL')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('hint', models.CharField(blank=True, default='', max_length=200, verbose_name='Hint')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('ancestor_folders', models.ManyToManyField(blank=True, related_name='ancestors_backref', to='maven.mediafolder')),
                ('child_folders', models.ManyToManyField(blank=True, related_name='children_backref', to='maven.mediafolder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_folders_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.CharField(max_length=250, unique=True, verbose_name='URL')),
                ('size', models.IntegerField(default=0, verbose_name='Size')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='maven.mediafolder')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFolderPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('visitors_can_view', models.BooleanField(default=True, verbose_name='Visitors can view?')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('admin_groups', models.ManyToManyField(blank=True, related_name='media_folder_admin_groups', to='auth.group', verbose_name='Admin Groups')),
                ('contrib_groups', models.ManyToManyField(blank=True, related_name='media_folder_contrib_groups', to='auth.group', verbose_name='Contributor Groups')),
                ('editor_groups', models.ManyToManyField(blank=True, related_name='media_folder_editor_groups', to='auth.group', verbose_name='Editor Groups')),
            ],
            options={
                'verbose_name_plural': 'Media folder policies (group permissions)',
            },
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='maven.mediafolderpolicy', verbose_name='Policy'),
        ),
    ]
