# Generated by Django 5.2.5 on 2025-09-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maven', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS maven_mediaexplorer',
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.DeleteModel(
                    name='MediaExplorer',
                ),
            ],
        ),
        migrations.CreateModel(
            name='MediaExplorerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Media Explorer',
                'verbose_name_plural': 'Media Explorer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('maven.mediafolder',),
        ),
    ]
