# Generated by Django 5.2.5 on 2025-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Title')),
                ('icon', models.CharField(verbose_name='Icon')),
                ('banner_bg_color', models.CharField(verbose_name='Banner Background Color')),
                ('banner_fg_color', models.CharField(verbose_name='Banner Foreground Color')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
